[2024-11-14T19:32:36.982+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-14T19:32:37.135+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_postgres_pipeline.create_tables scheduled__2023-01-16T00:00:00+00:00 [queued]>
[2024-11-14T19:32:37.179+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_postgres_pipeline.create_tables scheduled__2023-01-16T00:00:00+00:00 [queued]>
[2024-11-14T19:32:37.181+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-14T19:32:37.338+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): create_tables> on 2023-01-16 00:00:00+00:00
[2024-11-14T19:33:22.228+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=610) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-14T19:33:22.109+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'kafka_to_postgres_pipeline', 'create_tables', 'scheduled__2023-01-16T00:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/test_postgres.py', '--cfg-path', '/tmp/tmploa7erug']
[2024-11-14T19:33:22.413+0000] {standard_task_runner.py:105} INFO - Job 58: Subtask create_tables
[2024-11-14T19:33:22.413+0000] {standard_task_runner.py:72} INFO - Started process 651 to run task
[2024-11-14T19:33:40.155+0000] {cli_action_loggers.py:177} WARNING - Failed to log action (psycopg2.OperationalError) could not translate host name "postgres_local_container" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-11-14T19:33:40.648+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-14T19:33:44.329+0000] {job.py:229} INFO - Heartbeat recovered after 81.05 seconds
[2024-11-14T19:33:44.744+0000] {task_command.py:467} INFO - Running <TaskInstance: kafka_to_postgres_pipeline.create_tables scheduled__2023-01-16T00:00:00+00:00 [running]> on host 38e257a4ebe9
[2024-11-14T19:33:44.800+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-14T19:33:45.740+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='kafka_to_postgres_pipeline' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2023-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-16T00:00:00+00:00'
[2024-11-14T19:33:45.761+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-14T19:33:46.439+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-11-14T19:33:46.472+0000] {process_utils.py:132} INFO - Sending 15 to group 651. PIDs of all processes in the group: [651]
[2024-11-14T19:33:46.478+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 651
[2024-11-14T19:33:46.498+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-14T19:33:46.504+0000] {logging_mixin.py:190} INFO - Các bảng đã được tạo hoặc đã tồn tại.
[2024-11-14T19:33:46.540+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-14T19:33:46.655+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-14T19:33:46.659+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=kafka_to_postgres_pipeline, task_id=create_tables, run_id=scheduled__2023-01-16T00:00:00+00:00, execution_date=20230116T000000, start_date=20241114T193237, end_date=20241114T193346
[2024-11-14T19:33:46.792+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=651, status='terminated', exitcode=0, started='19:32:36') (651) terminated with exit code 0
[2024-11-14T19:33:46.803+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2024-11-14T19:33:47.044+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-14T19:33:49.224+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
