[2024-11-13T16:03:26.727+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-13T16:03:26.739+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: docker_build_and_run.docker_build manual__2024-11-13T16:03:24.175199+00:00 [queued]>
[2024-11-13T16:03:26.746+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: docker_build_and_run.docker_build manual__2024-11-13T16:03:24.175199+00:00 [queued]>
[2024-11-13T16:03:26.746+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-13T16:03:26.755+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): docker_build> on 2024-11-13 16:03:24.175199+00:00
[2024-11-13T16:03:26.761+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=213) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-13T16:03:26.763+0000] {standard_task_runner.py:72} INFO - Started process 214 to run task
[2024-11-13T16:03:26.762+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'docker_build_and_run', 'docker_build', 'manual__2024-11-13T16:03:24.175199+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/test_main.py', '--cfg-path', '/tmp/tmp2jpacoya']
[2024-11-13T16:03:26.763+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask docker_build
[2024-11-13T16:03:26.776+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-13T16:03:26.807+0000] {task_command.py:467} INFO - Running <TaskInstance: docker_build_and_run.docker_build manual__2024-11-13T16:03:24.175199+00:00 [running]> on host 0649263d7d26
[2024-11-13T16:03:26.874+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='docker_build_and_run' AIRFLOW_CTX_TASK_ID='docker_build' AIRFLOW_CTX_EXECUTION_DATE='2024-11-13T16:03:24.175199+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-13T16:03:24.175199+00:00'
[2024-11-13T16:03:26.881+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-13T16:03:26.897+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-11-13T16:03:26.914+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'docker build -t thaian2 -v /var/run/docker.sock:/var/run/docker.sock /opt/airflow/DeTaiPhanTichDinhLuong_Xuly_Pyspark_WebKimDong_BanChinh/DeTai_PhanTichDinhLuong_WebKimDong-main_version2_pyspark_windows']
[2024-11-13T16:03:26.925+0000] {subprocess.py:99} INFO - Output:
[2024-11-13T16:03:27.071+0000] {subprocess.py:106} INFO - DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
[2024-11-13T16:03:27.072+0000] {subprocess.py:106} INFO -             Install the buildx component to build images with BuildKit:
[2024-11-13T16:03:27.072+0000] {subprocess.py:106} INFO -             https://docs.docker.com/go/buildx/
[2024-11-13T16:03:27.073+0000] {subprocess.py:106} INFO - 
[2024-11-13T16:03:27.073+0000] {subprocess.py:106} INFO - unknown shorthand flag: 'v' in -v
[2024-11-13T16:03:27.073+0000] {subprocess.py:106} INFO - See 'docker build --help'.
[2024-11-13T16:03:27.074+0000] {subprocess.py:110} INFO - Command exited with return code 125
[2024-11-13T16:03:27.082+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2024-11-13T16:03:27.088+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=docker_build_and_run, task_id=docker_build, run_id=manual__2024-11-13T16:03:24.175199+00:00, execution_date=20241113T160324, start_date=20241113T160326, end_date=20241113T160327
[2024-11-13T16:03:27.097+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-13T16:03:27.098+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task docker_build (Bash command failed. The command returned a non-zero exit code 125.; 214)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2024-11-13T16:03:27.138+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-13T16:03:27.156+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-13T16:03:27.162+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
